
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/claims
    username: claim-user
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: 192.168.99.100
